language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

before_install:
  - mkdir build
  - mkdir build/logs

install:
  - composer install

env:
  - TESTER_PHP_BIN="php-cgi"

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -c test/php.ini --coverage ./build/logs/clover.xml --coverage-src ./src -s ./test/

after_failure:
  # Prints *.actual files content
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done